safe:        false
auto:        false
server:      false

source:      .
destination: ./_site

baseUrl    : http://jbee.github.com/
path       : /
cssPath    : /silk/assets/css
imgPath    : /silk/assets/img

markdown   : kramdown
pygments   : true

authorName : "Jan Bernitt"
authorFullName : "Jan Bernitt"
siteName   : "Silk Java IoC / DI"
siteDesc   : "The Silk Project Page"

exclude    : [ "README.md" ]